# -*- coding: utf-8 -*-
"""AI-RAG-PDF-Chatbot

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1ZxMu42_p30eBdCYKHVmS7gBUXBJWimO6
"""

# Install dependencies
!pip install -q gradio chromadb pypdf sentence-transformers google-generativeai

import gradio as gr
import chromadb
import google.generativeai as genai
import uuid
from pypdf import PdfReader
from sentence_transformers import SentenceTransformer

# ==============================
# Configure Gemini API
# ==============================
genai.configure(api_key="YOUR_GEMINI_API_KEY")   # <-- Replace with your API key

llm = genai.GenerativeModel("gemini-2.5-flash")

# ==============================
# Load Embedding Model
# ==============================
print("Loading embedding model...")
embedder = SentenceTransformer("all-MiniLM-L6-v2")
print("Embedding model loaded!")

# ==============================
# ChromaDB
# ==============================
client = chromadb.Client()
collection = client.get_or_create_collection("rag_docs")


# ==============================
# Extract text from PDF
# ==============================
def extract_text(pdf):
    reader = PdfReader(pdf.name)
    text = ""

    for page in reader.pages:
        page_text = page.extract_text()
        if page_text:
            text += page_text + "\n"

    return text


# ==============================
# Chunk text
# ==============================
def chunk_text(text, chunk_size=500, overlap=100):
    chunks = []
    start = 0

    while start < len(text):
        end = start + chunk_size
        chunks.append(text[start:end])
        start += chunk_size - overlap

    return chunks


# ==============================
# Upload PDF
# ==============================
def upload_pdf(pdf):
    global collection

    if pdf is None:
        return "Please upload a PDF."

    text = extract_text(pdf)

    if len(text.strip()) == 0:
        return "No readable text found in the PDF."

    chunks = chunk_text(text)

    embeddings = embedder.encode(chunks).tolist()

    # Delete previous collection
    try:
        client.delete_collection("rag_docs")
    except:
        pass

    collection = client.get_or_create_collection("rag_docs")

    collection.add(
        documents=chunks,
        embeddings=embeddings,
        ids=[str(uuid.uuid4()) for _ in chunks]
    )

    return f"✅ PDF Indexed Successfully!\nChunks Created: {len(chunks)}"


# ==============================
# Ask Question
# ==============================
def ask(question):

    if collection.count() == 0:
        return "Please upload and index a PDF first."

    query_embedding = embedder.encode(question).tolist()

    result = collection.query(
        query_embeddings=[query_embedding],
        n_results=5
    )

    docs = result.get("documents", [])

    if not docs or not docs[0]:
        return "I couldn't find the answer in the document."

    context = "\n".join(docs[0])

    context = context[:4000]

    prompt = f"""
You are a helpful AI assistant.

Answer ONLY using the context below.

If the answer is not present in the context, reply exactly:

I couldn't find the answer in the document.

Context:
{context}

Question:
{question}

Answer:
"""

    try:
        response = llm.generate_content(prompt)
        return response.text

    except Exception as e:
        return f"Error: {str(e)}"


# ==============================
# Gradio UI
# ==============================
with gr.Blocks(title="RAG PDF Chatbot") as demo:

    gr.Markdown("# 📄 RAG PDF Chatbot")
    gr.Markdown("Upload a PDF and ask questions from it.")

    pdf = gr.File(label="Upload PDF")

    upload_btn = gr.Button("Index PDF")

    status = gr.Textbox(label="Status")

    upload_btn.click(
        upload_pdf,
        inputs=pdf,
        outputs=status
    )

    question = gr.Textbox(
        label="Ask a Question",
        placeholder="Type your question here..."
    )

    ask_btn = gr.Button("Ask")

    answer = gr.Textbox(
        label="Answer",
        lines=10
    )

    ask_btn.click(
        ask,
        inputs=question,
        outputs=answer
    )

demo.launch(debug=True)